[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"

[profile.test]
verbosity = 2
gas_reports = ["*"]

[profile.production]
optimizer = true
optimizer_runs = 1000000
via_ir = true

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
